name: RewardsAPIPlugin
version: '${version}'
main: org.lushplugins.rewardsapi.RewardsAPIPlugin
api-version: '1.20'
softdepend:
  - floodgate
  - PlaceholderAPI
commands:
  rewardsapi:
    usage: /rewardsapi